language: c++

# Ubuntu 18.04
dist: bionic

install:
    # Install SFML from repositories
    - sudo apt-get install libsfml-dev
    # Install SFML dependencies, for SMFL fetch from Github
    #- sudo apt-get install libx11-dev libxrandr-dev libgl1-mesa-dev libudev-dev libfreetype6-dev libopenal-dev libvorbis-dev libflac-dev

script:
    # Build JaPomoC
    - mkdir -p build && cd build
    - cmake ..
    - make
