language: c++

before_install:
 # Add repository for more recent build tools
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq

install:
 # Give us a gcc version that supports C++11
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 # Install SFML dependencies
 - sudo apt-get install -qq libx11-dev libxrandr-dev libgl1-mesa-dev libx11-xcb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libudev-dev libglew-dev libjpeg8-dev libfreetype6-dev libopenal-dev libsndfile1-dev

before_script:
 # Export installed gcc
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
 # Build and install SFML
 - mkdir -p SFML_build && cd SFML_build
 - cmake ../lib/SFML
 - make
 - sudo make install
 - cd ..
 # Build JaPomoC
 - mkdir -p build && cd build
 - cmake ..
 - make
